const asyncActions = {
  USER_SIGN_IN_REQUEST: "USER_SIGN_IN_REQUEST",
  USER_SIGN_IN_SUCCESS: "USER_SIGN_IN_SUCCESS",
  USER_SIGN_IN_FAILURE: "USER_SIGN_IN_FAILURE",

  USER_SIGN_UP_REQUEST: "USER_SIGN_UP_REQUEST",
  USER_SIGN_UP_SUCCESS: "USER_SIGN_UP_SUCCESS",
  USER_SIGN_UP_FAILURE: "USER_SIGN_UP_FAILURE",

  USER_LOGOUT_REQUEST: "USER_LOGOUT_REQUEST",
  USER_LOGOUT_SUCCESS: "USER_LOGOUT_SUCCESS",
  USER_LOGOUT_FAILURE: "USER_LOGOUT_FAILURE",

  FETCH_LOGGED_IN_USER_REQUEST: "FETCH_LOGGED_IN_USER_REQUEST",
  FETCH_LOGGED_IN_USER_SUCCESS: "FETCH_LOGGED_IN_USER_SUCCESS",
  FETCH_LOGGED_IN_USER_FAILURE: "FETCH_LOGGED_IN_USER_FAILURE",
};

export default asyncActions;
